- name: set K8S_RESOURCE to correct var
  ansible.builtin.set_fact:
    k8s_resource_list: "{{ K8S_RESOURCE }}"
  when:  K8S_RESOURCE is not string

- name: convert K8S_RESOURCE to list if needed
  ansible.builtin.set_fact:
    k8s_resource_list: []
  when:  K8S_RESOURCE is string

- name: convert K8S_RESOURCE to list if needed
  ansible.builtin.set_fact:
    k8s_resource_list: "{{ k8s_resource_list + [K8S_RESOURCE] }}"
  when:  K8S_RESOURCE is string

- include_tasks: apply.yml
  loop: "{{ k8s_resource_list }}"

- name: Install, configure, and start Apache
  block:
    - name: TEMPLATE; create yaml ingress file for k8s apply
      template:
        src: "depingress.yaml.j2"
        dest: "depingress.yaml"

    - name: SHELL; install appy yaml ingress file
      shell:
        cmd:  kubectl apply -f depingress.yaml

  when: K3S_PORTS is defined and K3S_PORTS|length > 0
